-- PEGANDO TODOS OS CLIENTES
--SELECT * FROM TB_CUSTOMER;

-- PEGANDO A QUANTIDADE DE CLIENTES 
SELECT COUNT(*) FROM TB_CUSTOMER;

-- CONTANDO QUANTIDADE DE CLIENTES ATIVOS
SELECT COUNT (*) FROM TB_CUSTOMER
WHERE CUSTOMER_IS_ACTIVE = TRUE;

-- CONTANDO A QUANTIDADE DE CLIENTES INATIVOS
SELECT COUNT (*) FROM TB_CUSTOMER
WHERE CUSTOMER_IS_ACTIVE = FALSE;

-- CALCULANDO A PROPORÇÃO DE CLIENTES ATIVOS E INATIVOS
SELECT
    (COUNT(CASE WHEN CUSTOMER_IS_ACTIVE = TRUE THEN 1 END) - COUNT(CASE WHEN CUSTOMER_IS_ACTIVE = FALSE THEN 1 END)) * 100 / COUNT(CASE WHEN CUSTOMER_IS_ACTIVE = TRUE THEN 1 END) AS percentage_CUSTOMER_NOT_TURNOVER
FROM TB_CUSTOMER;

-- PEGANDO QUAIS TIPOS EXISGTENTES DE PEDIDOS
SELECT REQUEST_TYPE, COUNT|(*) FROM TB_REQUEST_CUSTOMER GROUP BY REQUEST_TYPE ORDER BY REQUEST_TYPE;

-- PEGANDO O TIPO DE CONTRATOS POSSIVEIS
SELECT CONTRACT_TYPE FROM TB_CONTRACT GROUP BY CONTRACT_TYPE ORDER BY CONTRACT_TYPE;

SELECT CUSTOMER_SECTOR, COUNT(*) AS total_customers
FROM TB_CUSTOMER
GROUP BY CUSTOMER_SECTOR
ORDER BY total_customers desc
limit 1;

-- DESCOBRINDO OS TIPOS DE CONTRATOS PREDOMINANTES EM CADA CLIENTE
select * from tb_customer;
select * from tb_contract;

SELECT A.CUSTOMER_NAME, B.CONTRACT_TYPE
FROM TB_CUSTOMER AS A
INNER JOIN TB_CONTRACT AS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID;


SELECT REQUEST_TYPE, COUNT(*) AS CONT
FROM TB_REQUEST_CUSTOMER
GROUP BY REQUEST_TYPE
ORDER BY REQUEST_TYPE;

SELECT CUSTOMER_ADDRESS, COUNT(*)
FROM TB_CUSTOMER
GROUP BY CUSTOMER_ADDRESS
ORDER BY CUSTOMER_ADDRESS




