CREATE TABLE TB_CUSTOMER
(CUSTOMER_ID SERIAL PRIMARY KEY,
CUSTOMER_NAME TEXT NOT NULL,
CUSTOMER_COMMERCIAL_EMAIL TEXT NOT NULL,
CUSTOMER_ADDRESS TEXT NOT NULL,
CUSTOMER_SECTOR TEXT NOT NULL,
CUSTOMER_IS_ACTIVE BOOLEAN NOT NULL)

CREATE TABLE TB_REQUEST_CUSTOMER
(REQUEST_ID SERIAL PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
REQUEST_TYPE TEXT NOT NULL,
REQUEST_NAME TEXT NOT NULL,
REQUEST_IS_POSSIBLE BOOLEAN NOT NULL,
CONSTRAINT FK_REQ_CUSTOMER FOREIGN KEY(CUSTOMER_ID) REFERENCES TB_CUSTOMER(CUSTOMER_ID))

CREATE TABLE TB_CONTRACT
(CONTRACT_ID SERIAL PRIMARY KEY,
CONTRACT_NAME TEXT NOT NULL,
CONTRACT_TYPE TEXT NOT NULL,
CUSTOMER_ID INT NOT NULL,
REQUEST_ID INT NOT NULL,
CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER(CUSTOMER_ID),
CONSTRAINT FK_REQ FOREIGN KEY (REQUEST_ID) REFERENCES TB_REQUEST_CUSTOMER(REQUEST_ID))

CREATE TABLE TB_EMPLOYEER (
    EMPLOYEER_ID SERIAL PRIMARY KEY,
    EMPLOYEER_NAME TEXT NOT NULL,
    EMPLOYEER_EMAIL_ADDRESS TEXT NOT NULL,
    EMPLOYEER_JOB TEXT NOT NULL,
    EMPLOYEER_DATE_OF_HIRING DATE NOT NULL,
    EMPLOYEER_IS_ACTIVE BOOLEAN NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    CONSTRAINT FK_EMP FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER(CUSTOMER_ID)
);
